# Set to true to add reviewers to pull requests
addReviewers: false

# Set to true to add assignees to pull requests
addAssignees: true

assignees:
  - imeoer
  - gaius-qi
  - bergwolf

numberOfAssignees: 3
