version: "2"

run:
  timeout: 10m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - misspell
    - unconvert

formatters:
  enable:
    - gofmt
    - goimports
