# https://golangci-lint.run/usage/configuration#config-file

linters:
  enable:
    - staticcheck
    - unconvert
    - gofmt
    - goimports
    - revive
    - ineffassign
    - govet
    - unused
    - misspell
  disable:
    - errcheck

run:
  timeout: 5m
issues:
  exclude-dirs:
    - misc