# https://golangci-lint.run/usage/configuration#config-file

version: "2"

linters:
  enable:
    - staticcheck
    - unconvert
    - gofmt
    - goimports
    - revive
    - ineffassign
    - govet
    - unused
    - misspell
  disable:
    - errcheck

run:
  deadline: 4m
