[package]
name = "zran"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.35"

[build-dependencies]
cc = "1.0.25"
anyhow = "*"
