name: CI

on:
  push:
    branches: [main, release-*]
  pull_request:
    branches: [main, release-*]

env:
  RUST_BACKTRACE: 1

jobs:
  check:
    name: Cargo check
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GH_TOKEN }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - name: Run cargo check
        run: |
          cargo check --all --all-targets

  lint:
    name: Golang lint
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Golangci lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.7
          working-directory: tests/integration

  test:
    name: Run tests
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GH_TOKEN }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov

      - name: Run tests
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info

  integration-tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout erofs-utils-rust
        uses: actions/checkout@v4
        with:
          path: erofs-utils-rust

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.5'

      - name: Build and install lepton binary
        run: |
          cd erofs-utils-rust
          cargo build --release
          sudo install -m 700 ./target/release/lepton /usr/sbin/

      - name: Run integration tests (verify + xfstests)
        run: |
          cd erofs-utils-rust
          make test-integration
