name: PR Label

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

permissions:
  contents: read

jobs:
  classify:
    name: Classify PR
    runs-on: ubuntu-latest
    steps:
      - name: PR impact specified
        uses: mheap/github-action-required-labels@23e10fde7e062233401931a0eece796cd9bf3177 # v5.5
        with:
          mode: exactly
          count: 1
          labels: 'bug, enhancement, documentation, dependencies'
